[package]
name = "adl"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A tool for managing your architecture decision records"
authors = [
    "Brad Cypert",
    "Mathias Panzenböck"
]

[dependencies]
httpdate = "1.0.3"
